learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
"""Define padrões de URL para learning_logs."""

from django.urls import path
from . import views

"""Define padrões de URL para learning_logs."""

app_name = 'learning_logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('new_topic', views.new_topic, name='new_topic'),
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    # Devemos adicionar um argumento topic_id no URL para adicionar uma nova
    # entrada, pois ela deve estar associada a um assunto em particular.
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
""" Define padrões de URL para users."""

from django.urls import path

# Importamos a view de login default
from django.contrib.auth.views import login
from . import views

app_name = 'users'

urlpatterns = [
    # Quando Django lê esse URL, a palavra users diz a ele para consultar
    # users/urls.py, e login lhe diz para enviar requisições à view login
    # default de Django(observe que o argumento da view é login, e não
    # views.login).Como não estamos escrevendo nossa própria função de view,
    # passamos um dicionário que diz ao Django em que lugar ele poderá
    # encontrar o template de login. Esse template fará parte da aplicação
    # users, e não de learning_logs.
    path('login/', login, {'template_name': 'users/login.html'}, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Onde criaremos nosso próprios modelos.
# Um modelo diz ao Django como trabalhar com os dados que serão armazenados na
# aplicação. Do ponto de vista do código, um modelo é apenas uma classe;
# ele tem atributos e métodos, assim como todas as classes.
# Criamos uma classe Topic, que herda de Model - uma classe pai incluída em
# Django, que define a funcionalidade básica de um modelo. A classe Topic tem
# apenas dois atributos, text e date_added.


class Topic(models.Model):
    """Um assunto sobre o qual o usuário está aprendendo."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    # Vincula o topic que está sendo criado com o autor.
    owner = models.ForeignKey(User, on_delete=True)

    def __str__(self):
        """Devolve uma representação em string do modelo Topic."""
        return self.text
        # Esse atributo é utilizado como default quando ele exibir informações
        # sobre o assunto.


class Entry(models.Model):
    """Algo específico aprendido sobre um assunto."""
    topic = models.ForeignKey(Topic, on_delete=True)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta: verbose_name_plural = 'entries'
    # A classe Meta armazena informações extras para administrar um modelo;
    # nesse caso, ela nos permite definir um atributo especial que diz ao
    # Django para usar Entries quando precisar se referir a mais de uma
    # entrada. (Sem isso, Django iria referenciar várias entradas como Entrys).
    #

    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + '...'
        return self.text

learning_logs/forms.py
from django import forms

# Importa os Modelos Topic e Entry para criar automaticamente os formulários.
from .models import Topic, Entry

# Definimos uma classe chamada TopicForm que herda de forms.ModelForm
class TopicForm(forms.ModelForm):
    # A versão mais simples de um ModelForm é constituída de uma classe Meta
    class Meta:
        # Diz ao Django em qual modelo o formulário deve se basear.
        # Criamos o formulário a partir do modelo Topic.
        model = Topic
        # Quais os campos devem ser incluídos nesse formulário.
        fields=['text']
        labels = {'text': ''}

# Definimos a classe chamada EntryForm que herda de forms.ModelForm
class EntryForm(forms.ModelForm):
    # A versão mais simples de um ModelForm é constituída de uma classe Meta
    class Meta:
        # Diz ao Django em qual modelo o formulário deve se basear.
        model = Entry
        # Quais os campos que serão inclusos nesses formulários
        fields = ['text']
        labels={'text': ''}
        # Um widget é um elemento de formulário HTML, por exemplo, uma caixa de texto de
        # uma única linha, uma área de texto com várias linhas ou uma lista suspensa.
        # Ao incluir o atirbuto widgets, podemos sobrescrever as opções default de
        # widgets de Django. Ao usar um elemento forms.Textarea, estamos personalizando
        # o widget de entrada para o campo 'text' de modo que a área de texto tenha 80
        # colunas, em vez de usar o default de 40.
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
# render renderiza a resposta de acordo com os dados fornecidos pelas views.
# redirect redireciona para a página selecionada.
# Request é um objeto de requisição.
from django.shortcuts import render, redirect

from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

# Importando o modelo associado que precisamos
from .models import Topic, Entry

# Importamos os formulários
from .forms import TopicForm, EntryForm

# @login_required
# Um decorador é uma diretiva colocada imediatamente antes da definição de uma
# função, que Python aplica a ela antes que seja executada a fim de alterar o
# modo como essa funçao se comporta
from django.contrib.auth.decorators import login_required


def index(request):
    """A página inicial de learning_logs."""
    # A função render utiliza dois argumentos, o objeto request original e um
    # template que pode ser usado para construir a página.
    return render(request, 'learning_logs/index.html')

# Aplicamos login_required() como um decorador da função de view topics()
# prefixando login_required com o símbolo @ para que Python saiba que deve
# executar o código em login_required() antes do código em topics().
# O código em login_required() verifica se um usuário está logado, e Django
# executará o código em topics() somente em caso afirmativo. Se não estiver
# logado, o usuário será redirecinado para a página de login.
# Para fazer esse redirecionamento funcionar, devemos modificar settings.py
# para que o Django saiba em que local pode encontrar a página login


@login_required
def topics(request):
    """Mostra todos os assuntos."""
    # Quando um usuário está logado, o objeto de requisição tem um atributo
    # request.user definido, que armazena informações sobre o usuário.
    # O fragmento de código Toopic.objects.filter(owner=request.user) diz ao
    # Django para recuperar apenas os objetos Topic do banco de dados cujo
    # atributo owner seja igual ao usuário atual. Como não estamos mudando o
    # modo como os assuntos são exibido, não é necessário alterar p template da
    # página de assuntos.
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    # Consultamos o banco de dados pedindo os objetos Topic, ordenados de
    # acordo com o atributo date_added. Armazenamos o queryset resultante em
    # topics.
    return render(request, 'learning_logs/topics.html', {'topics': topics})


@login_required
def topic(request, topic_id):
    """Mostra um único assunto e todas as suas entradas."""
    topic = Topic.objects.get(id=topic_id)
    # Garante que o assunto pertence ao usuário atual.

    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    return render(request, 'learning_logs/topic.html', {'topic': topic,
                                                        'entries': entries})

# A função de new_topic() deve tratar duas situações diferentes:
# Requisições iniciais para a página new_topic(caso em que o formulário em
# branco deverá ser mostrado) e o processamento de qualquer dado submetido
# no formulário que será redirecionado para learning_logs:topics.


@login_required
def new_topic(request):
    """Adiciona um novo assunto."""
    form = TopicForm(request.POST or None)
    # Não podemos salvar as informações submetidas no banco de dados antes de
    # verificar se são válidas. A função is_valid() verifica se todos os campos
    # necessários são preenchidos(todos os campos em um formulário são
    # obrigatórios por padrão) e se os dados fornecidos são do tipo esperado
    # para o campo.
    if form.is_valid():
        # Se tudo estiver válido, chamamos save(), que grava os dados do
        # formulário no banco de dados.
        # Quando chamamos form.save() pela primeira vez, passamos o argumento
        # commit=False poruqe precisamos modificar o novo assunto antes de
        # salválo no banco de dados. Então definimos o atributo owner do novo
        # assunto com o usuário atual. Por fim, chamamos sabe() na instância do
        # assunto que acabou de ser definido. Agora o assunto tem todos os
        # dados necessários e será salvo com sucesso.
        new_topic = form.save(commit=False)
        new_topic.owner = request.user
        new_topic.save()
        return redirect('learning_logs:topics')
    # Criamos uma instância de TopicForm, armazenamos essa instância em uma
    # variável form e enviamos o formulario para o template no dicionário de
    # contexto. Como não incluímos nenhum argumento ao instânciar TopicForm,
    # o Django cria um formulário em branco que o usuário poderá preencher.
    form = TopicForm()
    # Caso seja a primeira requisição, para criação de um novo topic.
    return render(request, 'learning_logs/new_topic.html', {'form': form})


@login_required
def new_entry(request, topic_id):
    """Acrescenta uma nova entrada para um assunto em particular."""
    # Recuperando o assunto que desejamos criar a entrada.
    topic = Topic.objects.get(id=topic_id)

    # Criamos uma instância de EntryForm preenchida com os dados de POST do
    # objeto request, e verificamos se o método da requisição é POST ou GET.
    form = EntryForm(request.POST or None)

    # Verificamos se o formulário é válido, se for, devemos definir o atributo
    # topic do objeto de entrada antes de salvá-lo no banco de dados.
    if form.is_valid():

        # Quando chamamos save(), incluímos o argumento commit=False para dizer
        # ao Django que crie um novo objeto de entrada e armazene em new_entry
        # sem salvá-lo no banco de dados por enquanto.
        new_entry = form.save(commit=False)

        # Definimos o atributo topic de new_entry com o assunto extraído do
        # banco de dados no início da função.
        new_entry.topic = topic

        # Chamamos save sem argumentos, essa instrução salva a entrada no banco
        # de dados com o assunto associado.
        new_entry.save()
        return HttpResponseRedirect(reverse('learning_logs:topic',
                                             args=[topic_id]))
        # Importamos a classe HttpResponseRedirect, que usaremos para
        # redirecionar o leitor de volta à página topics, depois que ele tiver
        # submetido o seu assunto. A função reverse() determina o URL a partir
        # de um padrão de URL nomeado, o que quer dizer que Django gerará o URL
        # quando a página dor solicitada.

    return render(request, 'learning_logs/new_entry.html', {'topic': topic,
                                                            'form': form})


@login_required
def edit_entry(request, entry_id):
    """Edita uma entrada existente."""
    # Adquirimos o objeto da entrada que o usuário quer editar e o assunto
    # associado a essa entrada.
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Criamos uma instância de EntryForm com o argumento instance=entry
        # Esse argumento diz ao Django para criar o formulário previamente
        # preenchido com informações do objeto de entrada existente. O usuário
        # verá os dados existentes e poderá editá-los
        form = EntryForm(instance=entry)
    else:
        # Ao processar uma requisição POST, passamos os argumentos
        # instance=entry e data=request.POST para dizer ao Django que crie uma
        # instância de formulário baseada nas informações associadas ao objeto
        # de entrada existente, atualizando com qualquer dado relevante de
        # request.POST.
        form = EntryForm(instance=entry, data=request.POST)

        # Se veio POST, validamos a requisição para ver se está tudo certo.
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                        args=[topic.id]))
    return render(request, 'learning_logs/edit_entry.html', {'entry': entry,
                                                             'topic': topic,
                                                             'form': form})

learning_logs/templates/learning_logs/base.html
<!-- Carregamos a coleção de tags de template disponíveis em
     django-bootstrap3 -->
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Learning Log</title>

    <!-- Usamos uma das tags de template personalizadas de django-bootstrap3,
         que diz ao Django para incluir todos os arquivos de estilização do
         Bootstrap -->
    {% bootstrap_css %}

    <!-- Habilita todos o comportamento interativo que possa ser usado em uma
         página, por exemplo, barra de navegação possíveis de serem
         contraídas -->
    {% bootstrap_javascript %}
  </head>

  <!-- Definindo a barra de navegação. -->
  <body>
    <!-- Static navbar -->

    <!-- O elemento <nav> que representa a seção de links de naveação da
         página. Tudo que estiver nesse elemento será estilizado de acrodo com
         as regras de estilo do Bootstrap definidas pelos seletores navbar,
         navbar-default e navbar-static-top. Um seletor determina a quais
         elementos de uma página uma determinada regra de estilo se aplica. -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">

          <!-- O template define um botão que aparecerá se a janela do
               navegador for estreita demais para exibir toda a barra de
               navagação horizontalmente. Quando o usuário clicar no botão, os
               elementos de navegação aparecerao em uma lista suspensa. A
               referência collapse faz a barra de navegação ser contraída
               quandoo usuário reduzir a janela do navegador ou quando o site
               for exibido em dispositivos móveis, com telas menores. -->
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>

          <!-- Configuramos o nome do projeto para que apareça na extremidade
               esquerda da barra de navegação e fizemos dele um link para a
               página inicial, pois essa informação aparecerá em todas as
               páginas do projeto. -->
          <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
            Learning Log
          </a>
        </div>

        <!-- Definimos um conjunto de links qe permite aos usuarios navegar
             pelo site. Uma barra de navegação é basicamente uma lista que
             começa com <ul> -->
        <div id="navbar" class="navbar-collapse collapse">

          <!-- Cada link é um item dessa lista(<li>). -->
          <ul class="nav navbar-nav">

            <!-- Para acrescentar mais links, insirimos outras linhas usando a
                 estrutura a seguir. -->
            <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
          </ul>

          <!-- Colocamos uma segunda lista de links de navegação, dessa vez
               usando um seletor navbar-right. Esse seletor estliza o conjunto
               de links par que ele apareça na borda direita da barra de
               navegação, em um local em que você normalmente vê links para
               login e para cadastramento. Nesse caso, exibiremos a saudação ao
               usuário e o link para logout ou os links para cadastramento ou
               login. -->
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Register</a></li>
              <li><a href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <!-- Definindo a parte principal da página. -->
    <div class="container">
      <div class="page-header">
        {% block header %} {% endblock header %}
      </div>
      <div>{% block content %} {% endblock content %}</div>
    </div> <!-- /container -->
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <!-- Dentro do action, na url passamos topic_id, para que na view possa
      associar a nova entrada ao assunto correto. -->
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  <p> Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">

    <!-- o Django usa a tag {% csrf_token %} para evitar que invasores usem o
         formulário a fim de terem acesso ao servidor -->
    {% csrf_token %}

    <!-- Nesse ponto exibimos o formulário. Basta incluirmos a variável de
         de template {{ form.as_p }}para que o framework cire todos os campos
         necessários e exiba o formulário automaticamente. O modificador as_p
         diz ao Django para renderizar todos os elementos do formulário em
         formato de parágrafo, que é uma maneira simples de exibir o formulário
         de modo organizado. -->
    {{ form.as_p }}

    <!-- O Django não cria um botão de submissão para os formulário, portanto
         definimos um em seguida -->
    <button name="submit">Save changes</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

<!-- Aqui definimos o que está no bloco header. -->
<!-- Em um elemento jumbotron, colocamos uma tagline concisa, Track yout
     learning, para da uma noção do que o Learning Log faz àqueles que
     visitarem o site pela primeira vez. -->
{% block header %}
  <div class='jumbotron'><h1>Track your learning.</h1></div>
{% endblock header %}

{% block content %}
  <!-- Link para registrar um novo usuário. -->
  <h2>
    <a href="{% url 'users:register' %}">Register account</a>
    to make your own Learning Log, and list the tpoics you're learning about.]
  </h2>

  <h2>
    Where never you learn somenting new about a topic, make an entry
    summarizing what you've learned.
  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
<!-- Mostramos o assunto para que o usuário saiba para que assunto está sendo
     criada a entrada. Esse item também atua como um link de volta para a página
     principal desse assunto -->
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>

  <!-- O argumento action do fomrilário inclui o valor topic_id no URL para
       que a função da view possa associar a nova entrada ao assunto correto -->
  <form action="{% url 'learning_logs:new_entry' topic.id%}" method="post">

    <!-- Para evitar que invasores usem o formulário a fim de ter acesso não
    autorizado ao servidor -->
    {% csrf_token %}

    {{ form.as_p }}
    <!-- Nesse ponto podemos ver como o Django simplica a execução de tarefas
         como a exibição de um formulário. Basta incluir a variável de template
         {{ form.as_p }} para que o framework crie todos os campos necessário e
         exiba o formulário automaticamente. O modificador as_p diz ao Django
         para renderizar todos os elementos do formulário em formato de
         parágrafo, que é uma maneira simples de exibir o formulário de modo
         organizado. -->

    <!-- O Django não cria um botão de submissão para os formulários, portanto
         definimos a seguir -->
    <button name='submit'>Add entry</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

<!-- Carregando as tags do bootstrap. -->
{% load bootstrap3 %}

{% block header %} <h2>Add a new topic</h2> {% endblock header %}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">

    <!-- O Django usa a tag 'csrf_token' para evitar que invasores usem o
    formulálrio a fim de ter acesso não autorizado ao servidor -->
    {% csrf_token %}

    {% bootstrap_form form %}

    <!-- O Django não cria um botão de submissão para os formulários,
    portanto definimos um em seguida. -->
    {% buttons %}
      <button name="submit" class='brn btn-primary'>Add topic</button>
      {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
<!-- Colocado o assunto no bloco header -->
{% block header %}<h2>{{ topic }}</h2>{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>
  <ul>

    <!-- Fazemos um for nas entradas para listar separadamente cada uma. -->
    {% for entry in entries %}
      <div class="panel panel-default">

        <!-- A div panel-heading contém a data da entrada e o link para
             editá-la. -->
        <div class="panel-heading">

          <!--  Exibimos o valor do atributo date_added. Nos templates
                do Django, uma linha vertical(|)representa um filtro de
                template - uma função que modifica o valor de uma linha
                variável de template. O filtro date:'M d, Y H:i' exibe
                timestamps no formato January 1, 2015 23:00. -->
          <h3>{{ entry.date_added|date:'M d, Y H:i' }}
            <small>
              <a
                href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry
              </a>
            </small>
          </h3>
        </div>

        <!-- Aqui temos a div panel-body, que contém o textp propriamente dito
             da entrada. -->
        <div class="panel-body"> {{entry.text|linebreaks }} </div>
      </div> <!-- panel -->
      {% empty %}
        There are no entries for this topic yet.
    {% endfor %}
  </ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        <h3>
      </li>
      {% empty %}
      <li>Nenhum assunto foi adicionado.</li>
    {% endfor %}
  </ul>
  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>
{% endblock content %}